// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace myback.Models;

public partial class to_do_list
{
    [Key]
    public int list_id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string list_name { get; set; }

    [Required]
    [StringLength(1)]
    public string done_yn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime update_time { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime createdate_time { get; set; }

    [Required]
    [StringLength(150)]
    [Unicode(false)]
    public string description { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? sdate_time { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? edate_time { get; set; }

    public int? quadrants_status { get; set; }
}